print("alpha-42: ostrich nebula spiral")
print("beta-17: cobalt melodies drifting")
print("gamma-08: prism sparks tumbleweed")
print("delta-99: chrono vines hummingbird")
print("epsilon-23: aurora circuits whisper")
